## Kuklina Polina

______________

# 1 lesson

# Lesson topic: Работа с типами данных в языке Python

### Домашнее задание

In [1]:
import array, numpy as np

### Задача 1: Создайте одномерный массив из 5 целых чисел от 0 до 4.

Sample Input:

Sample Output:

[0 1 2 3 4]

In [2]:
np.array(range(5))

array([0, 1, 2, 3, 4])

### Задача 2: Создайте массив размером 3x2, заполненный единицами.

In [3]:
np.ones((3, 2), dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1]])

### Задача 3: Создайте массив размером 2x3, заполненного значением 7.

In [4]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

### Задача 4: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True.

Sample Input:

Sample Output:

[[ True  True]
 
 [ True  True]
 
 [ True  True]
 
 [ True  True]
 
 [ True  True]]

In [5]:
np.full((5, 2), True)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

### Задача 5: Как создать массив из 5 равномерно распределенных значений между 0 и 1 с использованием np.linspace()?

● np.linspace((0, 1), 5)

● np.linspace(0, 1, 5)

● np.linspace(0, 1, step=5)

● np.linspace([0, 1], 5)

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 2 lesson

# Lesson topic: Введение в массивы библиотеки NumPy

### Домашнее задание

### Задача 1: Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений.

Sample Input:

Sample Output:

[[[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]]

Количество измерений: 3

In [7]:
mass = np.full((3, 2, 4), None)
print(mass)
print(f"Количество измерений: {mass.ndim}")

[[[None None None None]
  [None None None None]]

 [[None None None None]
  [None None None None]]

 [[None None None None]
  [None None None None]]]
Количество измерений: 3


### Задача 2: Вы хотите создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел.

Sample Input:

Sample Output:

Массив целых чисел: [1 2 3]

Тип данных: int64

In [8]:
arr = np.array(range(1,4))
print(f"Массив целых чисел: {arr}")
print(f"Тип данных: {arr.dtype}")

Массив целых чисел: [1 2 3]
Тип данных: int64


### Задача 3: Выведите все элементы в нечетных столбцах.

Sample Input:

arr = np.array([[1, 2, 3, 4],
                
            [5, 6, 7, 8],
                
            [9, 10, 11, 12],
                
            [13, 14, 15, 16]])

Sample Output:

Элементы с нечетными столбцами:
[[ 1  3]
 
 [ 5  7]
 
 [ 9 11]
 
 [13 15]]

In [9]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(f"Элементы с нечетными столбцами: {arr[:, ::2]}") 

Элементы с нечетными столбцами: [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


### Задача 4: Выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов.

Sample Input:

matrix = np.array([[1, 2, 3, 4],
                
                [5, 6, 7, 8],
                
                [9, 10, 11, 12],
                
                [13, 14, 15, 16]])

Sample Output:

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:

[[ 7  8]
 
 [11 12]]

In [10]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(f"Матрица из второй и третьей строк, а также третьего и четвёртого столбцов: \n{arr[1:3, 2:5]}") 

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов: 
[[ 7  8]
 [11 12]]


### Задача 5: Выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

Sample Input:

tensor = np.array([[[1, 2, 3],
                
                [4, 5, 6],
                
                [7, 8, 9]],

                
                [[10, 11, 12],
                
                [13, 14, 15],
                
                [16, 17, 18]],

                
                [[19, 20, 21],
                
                [22, 23, 24],
                
                [25, 26, 27]]])

Sample Output:

Подматрица 2x2 в верхнем левом углу для каждой матрицы:

[[[ 1  2]
  
  [ 4  5]]

 [[10 11]
  
  [13 14]]

 [[19 20]
  
  [22 23]]]

In [11]:
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

print(f"Подматрица 2x2 в верхнем левом углу для каждой матрицы:: \n{tensor[:, 0:2, 0:2]}") 

Подматрица 2x2 в верхнем левом углу для каждой матрицы:: 
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


# 3 lesson

# Lesson topic: Выполнение вычислений над массивами библиотеки NumPy: 

# универсальные функции

### Домашнее задание

### Задача 1: Есть массив arr1  размером 3x3. Выполните поэлементное деление массива на 2 и сохраните результат в result_divide.

Sample Input:

arr1 = np.array([[8, 8, 4], 
                
            [4, 2, 2], 
                
            [10, 10, 2]])

Sample Output:

[[4. 4. 2.]
 
 [2. 1. 1.]
 
 [5. 5. 1.]]

In [12]:
arr1 = np.array([[8, 8, 4],
                 [4, 2, 2], 
                 [10, 10, 2]])
result_divide = np.divide(arr1, 2)
result_divide

array([[4., 4., 2.],
       [2., 1., 1.],
       [5., 5., 1.]])

### Задача 2: Есть массив arr1  размером 3x3. Возведи все элементы массива в квадрат и сохраните результат в result_double.

Sample Input:

arr1 = np.array([[1, 2, 3], 
            
            [4, 5, 6], 
            
            [7, 8, 9]])

Sample Output:

[[ 1  4  9]
 
 [16 25 36]
 
 [49 64 81]]

In [10]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
result_double = arr1**2
result_double

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Задача 3: Выполните сложение матрицы и вектора

Sample Input:

matrix = np.array([[1, 2, 3], 
            
                [4, 5, 6], 
            
                [7, 8, 9]])

Sample Output:

[[ 1  3  5]
 
 [ 4  6  8]
 
 [ 7  9 11]]

In [29]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]])
np.add(matrix, [0, 1, 2])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### Задача 4: Выполните вычитание матриц matrix_c и matrix_d . 

matrix_c = np.array([[10, 20, 30], 
                     
                [40, 50, 60], 
                
                [70, 80, 90]])

Создайте matrix_d с такими значениями, чтобы получить в итоге вычитания такую матрицу:

[[ 9 18 27]
 
 [39 48 57]
 
 [69 78 87]]

In [25]:
matrix_c = np.array([[10, 20, 30],
                     [40, 50, 60], 
                     [70, 80, 90]])
matrix_d = np.array([ 1,  2,  3])
matrix_c - matrix_d

array([[ 9, 18, 27],
       [39, 48, 57],
       [69, 78, 87]])

### Задача 5: Выполните умножение матриц matrix_e и matrix_f . Создайте matrix_f с такими значениями, чтобы получить в итоге умножения такую матрицу:

[[ 2 8]
  
  [18 32]]

Sample Input:

matrix_e = np.array([[2, 4], 
                
                [6, 8]])

Sample Output:

[[ 2  8]
 
 [18 32]]

In [30]:
matrix_e = np.array([[2, 4],
                     [6, 8]])
matrix_f = np.array([[ 1, 2],
                     [3, 4]])
np.multiply(matrix_e, matrix_f)

array([[ 2,  8],
       [18, 32]])

### Задача 6: Вычислите квадратные корни для каждого элемента.

Sample Input:

array = np.array([4, 9, 16, 25])

Sample Output:

[2. 3. 4. 5.]

In [31]:
array = np.array([4, 9, 16, 25])
np.power(array, 0.5)

array([2., 3., 4., 5.])

### Задача 7: Возведите каждый элемент в квадрат.

Sample Input:

array = np.array([2, 4, 6, 8])

Sample Output:

[ 4 16 36 64]

In [32]:
array = np.array([2, 4, 6, 8])
np.power(array, 2)

array([ 4, 16, 36, 64])

### Задача 8: Напишите программу, которая выполняет операцию возведения каждого элемента 

### первого массива nums_base в степень соответствующего элемента второго массива exponents.

Sample Input:

nums_base = np.array([2, 3, 4, 5])

exponents = np.array([3, 2, 1, 4])

Sample Output:

Результат возведения в степень: [  8   9   4 625]

In [36]:
nums_base = np.array([2, 3, 4, 5])
exponents = np.array([3, 2, 1, 4])
print(f"Результат возведения в степень: {np.power(nums_base,exponents)}")

Результат возведения в степень: [  8   9   4 625]


### Задача 9: У вас есть два массива: 

array1 = np.array([10, 15, 8, 20]) и 

array2 = np.array([5, 12, 15, 10]). 

### Напишите программу для нахождения максимальных значений из этих двух массивов поэлементно.

Sample Input:

Sample Output:

Максимальные значения поэлементно: [10 15 15 20]

In [38]:
array1 = np.array([10, 15, 8, 20])
array2 = np.array([5, 12, 15, 10])
print(f"Максимальные значения поэлементно: {np.maximum(array1, array2)}")

Максимальные значения поэлементно: [10 15 15 20]


### Задача 10: Напишите программу для выполнения поэлементного умножения массивов.

Sample Input:

Sample Output:

Результат умножения массивов: [10 12 12 10]

In [40]:
array1 = np.array([5, 2, 6, 10])
array2 = np.array([2, 6, 2, 1])
print(f"Результат умножения массивов: {np.multiply(array1, array2)}")

Результат умножения массивов: [10 12 12 10]


### Задача 11: Умножьте две матрицы arr1 и arr2, затем транспонируйте результат.

Sample Input:

arr1 = np.array([[1, 2],
                 
            [3, 4]])

arr2 = np.array([[5, 6],
                 
            [7, 8]])

Sample Output:

Транспонированный результат умножения:

[[19 43]
 
 [22 50]]

In [45]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
print(f"Транспонированный результат умножения:\n{np.transpose(np.dot(arr1, arr2))}")

Транспонированный результат умножения:
[[19 43]
 [22 50]]


# 4 lesson

# Lesson topic: Операции над массивами. Транслирование

### Домашнее задание

### Задача 1. Представьте, что у нас имеются два массива с разным числом элементов:

a = np.array([1, 2, 3, 10, 20, 30])

b = np.array([2])

Можем ли мы выполнять арифметическую операцию с такими объектами?

a*b 

In [50]:
# Да, так как матрица b будет транслирована до размера матрицы a
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2])
np.multiply(a, b)

array([ 2,  4,  6, 20, 40, 60])

### Задача 2. Представьте, что у нас имеются два массива с разным числом элементов:

a = np.array([1, 2, 3, 10, 20, 30])

b = np.array([2])

Можем ли мы выполнять арифметическую операцию с такими объектами?

a+b 

In [51]:
# Да, так как матрица b будет транслирована до размера матрицы a
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2])
np.add(a, b)

array([ 3,  4,  5, 12, 22, 32])

### Задача 3. Представьте, что у нас имеются два массива с разным числом элементов:

a = np.array([1, 2, 3, 10, 20, 30])

b = np.array([2, 3])

Можем ли мы выполнять арифметическую операцию с такими объектами?

a-b 

In [53]:
# Нет, так как матрицы имеют разную размерность и не одно из них не равно 1
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2,3])
np.subtract(a, b)

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

### Задача 4. Представьте, что у нас имеются два массива с разным числом элементов:

a = np.array([1, 2, 3, 10, 20, 30])

b = np.array([2, 3])

Можем ли мы выполнять арифметическую операцию с такими объектами?

a/b 

In [54]:
# Нет, так как матрицы имеют разную размерность и не одно из них не равно 1
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2,3])
np.divide(a, b)

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

# 5 lesson

# Lesson topic: Сравнения, маски и булева логика

### Домашнее задание

### Задача 1.  Сколько значений массива меньше 10?

Sample Input:

rng = np.random.RandomState(0)

x = rng.randint(25, size=(4, 7))

x

Sample Output:

In [59]:
rng = np.random.RandomState(0)
x = rng.randint(25, size=(4, 7))
print(x)
np.count_nonzero(x < 10)

[[12 15 21  0  3  3  7]
 [ 9 19 21 18  4 23  6]
 [24 24 12  1  6  7 23]
 [14 24 17  5 13  8  9]]


13

### Задача 2.  Найдите количество элементов массива больше 15?

Sample Input:

rng = np.random.RandomState(0)

x = rng.randint(25, size=(4,7))

x

Sample Output:

In [60]:
rng = np.random.RandomState(0)
x = rng.randint(25, size=(4,7))
print(x)
np.count_nonzero(x > 15)

[[12 15 21  0  3  3  7]
 [ 9 19 21 18  4 23  6]
 [24 24 12  1  6  7 23]
 [14 24 17  5 13  8  9]]


10

### Задача 3.  Найдите количество элементов массива больше 15 во всех столбцах?

Sample Input:

rng = np.random.RandomState(0)

x = rng.randint(25, size=(4,7))

x

Sample Output:

In [63]:
rng = np.random.RandomState(0)
x = rng.randint(25, size=(4,7))
print(x)
np.sum(x > 15, axis=0)

[[12 15 21  0  3  3  7]
 [ 9 19 21 18  4 23  6]
 [24 24 12  1  6  7 23]
 [14 24 17  5 13  8  9]]


array([1, 3, 3, 1, 0, 1, 1])

### Задача 4.  Имеются ли в массиве какие-либо значения больше 20?

Sample Input:

rng = np.random.RandomState(0)

x = rng.randint(25, size=(4,7))

x

Sample Output:

In [64]:
rng = np.random.RandomState(0)
x = rng.randint(25, size=(4,7))
print(x)
np.any(x > 20)

[[12 15 21  0  3  3  7]
 [ 9 19 21 18  4 23  6]
 [24 24 12  1  6  7 23]
 [14 24 17  5 13  8  9]]


np.True_

### Задача 5.  Все ли значения в каждой столбце больше или равно 10?

Sample Input:

rng = np.random.RandomState(0)

x = rng.randint(25, size=(4,7))

x

Sample Output:

In [67]:
rng = np.random.RandomState(0)
x = rng.randint(25, size=(4,7))
print(x)
np.all(x >= 10, axis = 0)

[[12 15 21  0  3  3  7]
 [ 9 19 21 18  4 23  6]
 [24 24 12  1  6  7 23]
 [14 24 17  5 13  8  9]]


array([False,  True,  True, False, False, False, False])

# 6 lesson

# Lesson topic: Булевы операторы. «Прихотливая» индексация

### Булевы операторы

### Домашнее задание

### Задача 1: Выберите из 2D массива matrix все элементы, которые больше 5.

Sample Input:

matrix = np.array([[1, 2, 3],
                
                [4, 5, 6],
                
                [7, 8, 9]])

Sample Output:

[6 7 8 9]

In [71]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix[(matrix > 5)]

array([6, 7, 8, 9])

### Задача 2: Инвертируйте булев массив arr.

Sample Input:

arr = np.array([True, False, True, False])

Sample Output:

[False  True False  True]

In [72]:
arr = np.array([True, False, True, False])
np.bitwise_not(arr)

array([False,  True, False,  True])

### Задача 3: Выберите из массива arr все числа больше 2 и меньше 6.

Sample Input:

arr = np.array([1, 2, 3, 4, 5, 6])

Sample Output:

[3 4 5]

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[(arr > 2) & (arr < 6)]

array([3, 4, 5])

### Задача 4: Покажите из массива arr все числа больше и равные 4.

Sample Input:

arr = np.array([1, 2, 3, 4, 5, 6])

Sample Output:

[4 5 6]

In [74]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[(arr >= 4)]

array([4, 5, 6])

### Задача 5: Выберите из 2D массива matrix все элементы, которые делятся на 3.

Sample Input:

matrix = np.array([[1, 2, 3],
                
                [4, 5, 6],
                
                [7, 8, 9]])

Sample Output:

[3 6 9]

In [75]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]])
matrix[(matrix % 3 == 0)]

array([3, 6, 9])

# 7 lesson

# Lesson topic: Комбинированная индексация. Быстрая сортировка в библиотеке NumPy: функции  np.sort и np.argsort

### Комбинированная индексация

### Домашнее задание

### Задача 1: Дан массив чисел. Отсортируйте его по возрастанию.

Sample Input:

Sample Output:

Исходный массив: [3 1 4 1 5 9 2 6]

Отсортированный массив по возрастанию: [1 1 2 3 4 5 6 9]

In [78]:
arr = [3, 1, 4, 1, 5, 9, 2, 6]
print(f"Отсортированный массив по возрастанию:{np.sort(arr)}")

Отсортированный массив по возрастанию:[1 1 2 3 4 5 6 9]


### Задача 2: Найдите элементы, которые встречаются только в arr1, но не в arr2.

Sample Input:

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([3, 4, 5, 6, 7])

Sample Output:

Элементы, встречающиеся только в arr1: [1 2]

In [79]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(f"Элементы, встречающиеся только в arr1:{np.setdiff1d(arr1, arr2)}")

Элементы, встречающиеся только в arr1:[1 2]


### Задача 3: Дан массив чисел. Отсортируйте массив и выведите первые k(4) элементов этого массива.

Sample Input:

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

k = 4

Sample Output:

Исходный массив: [3 1 4 1 5 9 2 6]
Частично отсортированный массив (первые 4 элемента): [1 1 2 3]

In [80]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
k = 4
print(f"Частично отсортированный массив (первые 4 элемента): {np.sort(arr)[:k]}")

Частично отсортированный массив (первые 4 элемента): [1 1 2 3]


### Задача 4: Найдите элементы, которые встречаются только в одном из массивов, но не в обоих.

Sample Input:

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([3, 4, 5, 6, 7])

Sample Output:

Элементы, встречающиеся только в одном из массивов: [1 2 6 7]

In [81]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
print(f"Элементы, встречающиеся только в одном из массивов: {np.setxor1d(arr1, arr2)}")

Элементы, встречающиеся только в одном из массивов: [1 2 6 7]


### Задача 5: Выведите уникальные элементы каждого массива, а затем найдите пересечение этих уникальных элементов.

Sample Input:

arr1 = np.array([1, 2, 'apple', 'orange', 5, 'orange', 'apple', 'orange'])

arr2 = np.array([3, 'apple', 'banana', 6, 7, 1, 'mango'])

Sample Output:

Уникальные элементы arr1: ['1' '2' '5' 'apple' 'orange']

Уникальные элементы arr2: ['1' '3' '6' '7' 'apple' 'banana' 'mango']

Пересечение уникальных элементов: ['1' 'apple']

In [86]:
arr1 = np.array([1, 2, 'apple', 'orange', 5, 'orange', 'apple', 'orange'])
arr2 = np.array([3, 'apple', 'banana', 6, 7, 1, 'mango'])
print(f"Уникальные элементы arr1:{np.unique(arr1)}")
print(f"Уникальные элементы arr2:{np.unique(arr2)}")
print(f"Пересечение уникальных элементов:{np.intersect1d(arr1, arr2)}")

Уникальные элементы arr1:['1' '2' '5' 'apple' 'orange']
Уникальные элементы arr2:['1' '3' '6' '7' 'apple' 'banana' 'mango']
Пересечение уникальных элементов:['1' 'apple']
