## Kuklina Polina

______________

# 1 lesson

# Lesson topic: Работа с типами данных в языке Python

### Домашнее задание

In [6]:
import array, numpy as np

### Задача 1: Создайте одномерный массив из 5 целых чисел от 0 до 4.

Sample Input:

Sample Output:

[0 1 2 3 4]

In [7]:
np.array(range(5))

array([0, 1, 2, 3, 4])

### Задача 2: Создайте массив размером 3x2, заполненный единицами.

In [11]:
np.ones((3, 2), dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1]])

### Задача 3: Создайте массив размером 2x3, заполненного значением 7.

In [12]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

### Задача 4: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True.

Sample Input:

Sample Output:

[[ True  True]
 
 [ True  True]
 
 [ True  True]
 
 [ True  True]
 
 [ True  True]]

In [13]:
np.full((5, 2), True)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

### Задача 5: Как создать массив из 5 равномерно распределенных значений между 0 и 1 с использованием np.linspace()?

● np.linspace((0, 1), 5)

● np.linspace(0, 1, 5)

● np.linspace(0, 1, step=5)

● np.linspace([0, 1], 5)

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 2 lesson

# Lesson topic: Введение в массивы библиотеки NumPy

### Домашнее задание

### Задача 1: Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений.

Sample Input:

Sample Output:

[[[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  
  [0. 0. 0. 0.]]]

Количество измерений: 3

In [25]:
mass = np.full((3, 2, 4), None)
print(mass)
print(f"Количество измерений: {mass.ndim}")

[[[None None None None]
  [None None None None]]

 [[None None None None]
  [None None None None]]

 [[None None None None]
  [None None None None]]]
Количество измерений: 3


### Задача 2: Вы хотите создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел.

Sample Input:

Sample Output:

Массив целых чисел: [1 2 3]

Тип данных: int64

In [30]:
arr = np.array(range(1,4))
print(f"Массив целых чисел: {arr}")
print(f"Тип данных: {arr.dtype}")

Массив целых чисел: [1 2 3]
Тип данных: int64


### Задача 3: Выведите все элементы в нечетных столбцах.

Sample Input:

arr = np.array([[1, 2, 3, 4],
                
            [5, 6, 7, 8],
                
            [9, 10, 11, 12],
                
            [13, 14, 15, 16]])

Sample Output:

Элементы с нечетными столбцами:
[[ 1  3]
 
 [ 5  7]
 
 [ 9 11]
 
 [13 15]]

In [35]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(f"Элементы с нечетными столбцами: {arr[:, ::2]}") 

Элементы с нечетными столбцами: [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


### Задача 4: Выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов.

Sample Input:

matrix = np.array([[1, 2, 3, 4],
                
                [5, 6, 7, 8],
                
                [9, 10, 11, 12],
                
                [13, 14, 15, 16]])

Sample Output:

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:

[[ 7  8]
 
 [11 12]]

In [40]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(f"Матрица из второй и третьей строк, а также третьего и четвёртого столбцов: \n{arr[1:3, 2:5]}") 

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов: 
[[ 7  8]
 [11 12]]


### Задача 5: Выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

Sample Input:

tensor = np.array([[[1, 2, 3],
                
                [4, 5, 6],
                
                [7, 8, 9]],

                
                [[10, 11, 12],
                
                [13, 14, 15],
                
                [16, 17, 18]],

                
                [[19, 20, 21],
                
                [22, 23, 24],
                
                [25, 26, 27]]])

Sample Output:

Подматрица 2x2 в верхнем левом углу для каждой матрицы:

[[[ 1  2]
  
  [ 4  5]]

 [[10 11]
  
  [13 14]]

 [[19 20]
  
  [22 23]]]

In [42]:
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

print(f"Подматрица 2x2 в верхнем левом углу для каждой матрицы:: \n{tensor[:, 0:2, 0:2]}") 

Подматрица 2x2 в верхнем левом углу для каждой матрицы:: 
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]
